server.port = 9095
spring.config.import=classpath:data/testng.xml
spring.app.nidNo=6015326314
#spring.config.import=file:./testng.xml,optional:file:/Users/home/config/testng.xml
##spring.config.import=./testng.xml
#spring.config.import=./src/main/resources/testng.xml
name_prop=shihab
phn_number=01620210927
deviceType=ANDROID
pin_prop=1590
role_prop=CUSTOMER
nid_no_prop=6015326314
nid_type_prop=SMART_CARD
ec_eng_name_prop=A.B.M.Shihab Uddin
spring.main.allow-bean-definition-overriding=true
auth_token=eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJleUxVOEdQdjJtcTZVM0taMTl0Vy13M2ZpMjRWRHZ5R3o5N3pLVkM0ZFBBIn0.eyJleHAiOjE4MDgzNzQ4NTQsImlhdCI6MTY1Mjg1NDg1NCwianRpIjoiODEzNWJkYmUtNzA5Zi00N2U5LWE2MDItZDlhZDc0ODllNWRlIiwiaXNzIjoiaHR0cDovLzEwLjkuMC43Nzo2MDcwL2F1dGgvcmVhbG1zL3RhbGx5S2hhdGEiLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiODE3Y2YwODMtZTUwMS00NDUzLWExMzctMmQ1ZGJjYzYyN2MwIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoidGFsbHlLaGF0YSIsImFjciI6IjEiLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiY2xpZW50SG9zdCI6IjEwLjEwLjkuOTQiLCJjbGllbnRJZCI6InRhbGx5S2hhdGEiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJzZXJ2aWNlLWFjY291bnQtdGFsbHlraGF0YSIsImNsaWVudEFkZHJlc3MiOiIxMC4xMC45Ljk0In0.axpP0ChUYy_37UPQzzupuj0a4i4bERvnMrCnnh3mGTT4YDqyrVpam5ucnys0VCr1HfEFpfNxM4c7HMnu0sGNCEQtvC4TP959x7WKZWxikOCLOoJZU1jZOesUDTklT9eRLNDriGEn5UWUqtxsbyiCy8EpRD7qx7YPN7o1-qHPEjgDTOpLuvLbxfDpYdKl_ox0qbMCEF9tX4LK3aLwn39owZ8H4kMin-DqNc93CQyQuwlXwlMVn3w64SjmZabKhmqS0OQB3fIJWY3pogVHUw72CwkkEgK7U4RVPXzLepo2U5qCDKkp6DmRxcqtrpK_ke9D2YSHgffpKEsqYFhtd9XTOg

# attach bank mfs properties

otp_verified_prop=true
accountType_prop=MFS
account_type_prop=MFS
mfs_type_prop=BKASH
wallet_no_prop=01621215877

# npsb credit properties
receiver_wallet_no=9100511311374454
external_account_no=01621215882
external_account_name=test
external_FI=1005
amount=70
trace_id=123456
storeLabel=194
terminalLabel=179

#login properties
deviceId_prop=3eb0485a5030d0e9
device_type_prop=ANDROID
uuid_prop=0069a6b1-b510-443b-b51b-db84889ef9f6

# recharge properties
mobile_operator_prop=TT
mobile_type_prop=PREPAID
is_fp_auth_prop=false
amount_prop=12.01

#send money properties
receiver_prop=01715322259

#cash out properties
financialInstitute_prop=NAGAD
toAc_prop=01621215877
channel_prop=tally

#update user type properties
userType_prop=MERCHANT
remarks_prop="user type change"