server.port = 9095
spring.config.import=classpath:data/testng.xml
spring.app.nidNo=6015326314
#spring.config.import=file:./testng.xml,optional:file:/Users/home/config/testng.xml
##spring.config.import=./testng.xml
#spring.config.import=./src/main/resources/testng.xml
name_prop=shihab
phn_number=01970002184
deviceType=ANDROID
pin_prop=1590
role_prop=CUSTOMER
nid_no_prop=6015326314
nid_type_prop=LEGACY_NID
ec_eng_name_prop=A.B.M.Shihab Uddin
spring.main.allow-bean-definition-overriding=true
auth_token=eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJleUxVOEdQdjJtcTZVM0taMTl0Vy13M2ZpMjRWRHZ5R3o5N3pLVkM0ZFBBIn0.eyJleHAiOjE4MDgzNzQ4NTQsImlhdCI6MTY1Mjg1NDg1NCwianRpIjoiODEzNWJkYmUtNzA5Zi00N2U5LWE2MDItZDlhZDc0ODllNWRlIiwiaXNzIjoiaHR0cDovLzEwLjkuMC43Nzo2MDcwL2F1dGgvcmVhbG1zL3RhbGx5S2hhdGEiLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiODE3Y2YwODMtZTUwMS00NDUzLWExMzctMmQ1ZGJjYzYyN2MwIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoidGFsbHlLaGF0YSIsImFjciI6IjEiLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiY2xpZW50SG9zdCI6IjEwLjEwLjkuOTQiLCJjbGllbnRJZCI6InRhbGx5S2hhdGEiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJzZXJ2aWNlLWFjY291bnQtdGFsbHlraGF0YSIsImNsaWVudEFkZHJlc3MiOiIxMC4xMC45Ljk0In0.axpP0ChUYy_37UPQzzupuj0a4i4bERvnMrCnnh3mGTT4YDqyrVpam5ucnys0VCr1HfEFpfNxM4c7HMnu0sGNCEQtvC4TP959x7WKZWxikOCLOoJZU1jZOesUDTklT9eRLNDriGEn5UWUqtxsbyiCy8EpRD7qx7YPN7o1-qHPEjgDTOpLuvLbxfDpYdKl_ox0qbMCEF9tX4LK3aLwn39owZ8H4kMin-DqNc93CQyQuwlXwlMVn3w64SjmZabKhmqS0OQB3fIJWY3pogVHUw72CwkkEgK7U4RVPXzLepo2U5qCDKkp6DmRxcqtrpK_ke9D2YSHgffpKEsqYFhtd9XTOg

# attach bank mfs properties

otp_verified_prop=true
accountType_prop=MFS
account_type_prop=MFS
mfs_type_prop=BKASH
wallet_no_prop=01621215877

# npsb credit properties
receiver_wallet_no=9100511311374454
external_account_no=01621215882
external_account_name=test
external_FI=1005
amount=17.00
trace_id=123456
storeLabel=194
terminalLabel=179

#login properties
deviceId_prop=3eb0485a5030d0e9
device_type_prop=ANDROID
uuid_prop=bd5b6dbd-f479-433e-8fb3-d4eda8fa5906

# recharge properties
mobile_operator_prop=TT
mobile_type_prop=PREPAID
is_fp_auth_prop=false
amount_prop=12.01

#send money properties
receiver_prop=01715322259

# nagad cash out properties
financialInstitute_prop1=NAGAD
toAc_prop1=01621215877
channel_prop=tally

# rocket cash out properties
toAc_prop2 = 019800016669
financialInstitute_prop2 = ROCKET

#update user type properties
userType_prop=MERCHANT
remarks_prop=user type change

## pre-active to active properties
status_prop=APPROVE
externalUserName_prop=UPMS

## cash in properties
cash_in_amount_prop = 200
card_gateway_prop = EBL
card_no_mask_prop = 222300xxxxxx0007
card_type_prop = MASTERCARD

## FO Login properties
externalFi_prop = TALLY_FO
userId_prop = tc_portal
password_prop = NP@007!

## insert biz user info properties
city_prop = Thakurgaon
bizName_prop = test plus
bizNameBn_prop =  ???? ?????34???!??? 
bizType_prop = TK_MERCHANT
upazila_prop = Chitalmari
shopAddress_prop = Pabna
merchantCategoryCode_prop = null

## bank cash out properties
routing_no_prop_1 = 145060826
account_no_prop_1 = 1311000476899
amount_bank_cashout_prop = 2.12
bankCode_prop = 145
instantTransfer_prop = true

## add MTB bank properties
account_name_prop_1 = Shihab MTB Bank
bank_name_prop_1 = Mutual Trust Bank Ltd.

## add CBL bank properties
account_name_prop_2 = Shihab CBL Bank
bank_name_prop_2 = The City Bank PLC
account_no_prop_2 = 1311222476899
routing_no_prop_2 = 225060283

## add uttara bank properties
account_name_prop_3 = Shihab Uttara Bank
bank_name_prop_3 = Uttara Bank PLC
account_no_prop_3 = 1311222476800
routing_no_prop_3 = 250010079

# visa transfer properties
primaryAccountNumber_prop = 4515960508047342
visa_amount_prop = 10.13
visa_channel_prop = VISA
txnType_prop = VISA_TRANSFER
cardType_prop = D
instantTransferEnabled_prop = true
bankName_prop = EBL
note_prop = test

# nagad add money properties
URLNagad=https://stgnpapigw.nobopay.com/api/payment/nagad/checkout/01715322230/20
NagadAcc=01621215877
NagadPIN=1212

# nagad credit collection properties
amount_CreditCollection=11
credit_collection_receiver=01715322230
srcNagadNo=01517000123
externalFI_prop = NAGAD
CCNagadAmount=11

##Credit collection url
CCUrl=https://tally.pe/n4GKP

## add money card properties
URL=https://stgnpapigw.nobopay.com/api/payment/create/order/01715322230/100.0
add_money_card_amount=25
cardName=test sqa
cardNo=5111111111111118
cardExpMonth=01
cardExpYear=39
securityCode=100

## tm purchase properties
tm_purchase_amount_prop = 2
tm_purchase_externalData_prop = Low price 2 taka
